name: analyses
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:



  perfrom_analyses:
    permissions:
      contents: write
    uses: ./.github/workflows/CI-env.yml
    with:
      folder: AiTestGenerotorAnalisis
      script: RunAnalysis.sh
      commit-result: true
