name: analyses
on: push

jobs:
  permissions:
    contents: write
  uses: ./.github/workflows/CI-env.yml
  with:
    folder: AiTestGenerotorAnalisis
    script: RunAnalisis.sh
    commit-result: true
