name: analyses
on:
  push:
    branches:
      - master

jobs:
  perfrom_analyses:
    permissions:
      contents: write
      id-token: write
      pages: write
    uses: ./.github/workflows/CI-env.yml
    with:
      folder: AiTestGenerotorAnalisis
      script: RunAnalysis.sh
      commit-result: true
  Deploy_webpage:
    needs: perfrom_analyses
    permissions:
      contents: write
      id-token: write
      pages: write
    uses: ./.github/workflows/CI-env.yml
    with:
      folder: AiTestGenerotorAnalisis
      script: BuildWebpage.sh
      publish-webpage: true