name: pipeline

on:
    push


jobs:
    build-plugin:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: .

        steps:
            - name: install depndecies
              run: |
                    sudo apt update
                    sudo  apt install git
                    sudo  apt-get install -y dos2unix

            - name: Set git to use LF
              run: |
                  git config --global core.autocrlf false
                  git config --global core.eol lf
            - uses: actions/checkout@v3
            - name: Set up JDK 17
              uses: actions/setup-java@v3
              with:
                java-version: '17'
                distribution: 'temurin'
                cache: maven
            - name: Grant execute permission for Gradle wrapper
              run: |
                    cd AiUnitTestPlugin
                    echo "Listing files in workspace:"
                    ls -al
                    chmod +x gradlew
            - name: Build with Gradle
              run: |
                    cd AiUnitTestPlugin
                    ls -al
                    dos2unix gradlew
                    ./gradlew build -x test 
    run-project-test:
      runs-on: ubuntu-latest
      steps:
      - name: install depndecies
        run: |
                    sudo apt update
                    sudo  apt install git
                    sudo  apt-get install -y dos2unix
      - name: Set up JDK 17
        run: |
          sudo apt-get install -y openjdk-17-jdk

      - name: install docker
        run: |
          sudo apt-get update
          sudo apt-get install ca-certificates curl
          sudo install -m 0755 -d /etc/apt/keyrings
          sudo curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
          sudo chmod a+r /etc/apt/keyrings/docker.asc
          echo \
            "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu \
            $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | \
            sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
          sudo apt-get update
          sudo apt-get install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin -y
          sudo docker run hello-world
      - name: print docker info
        run: |
          docker info
          ls /etc/docker
          docker ps
          ls /sys/fs/cgroup/
          run: echo "$DOCKER_HOST"




      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: run test
        run: |
                  cd AiUnitTestPlugin
                  dos2unix gradlew
                  chmod +x gradlew
                  ./gradlew test 
                  



