name: pipeline

on: push

jobs:
  run-project-test:
    permissions:
      contents: write
    uses: ./.github/workflows/CI-env.yml
    with:
      folder: AiTestGenerator
      script: AiTestGeneratorTests.sh
 run-analyiss-test:
   # needs: run-project-test
   permissions:
     contents: write
   uses: ./.github/workflows/CI-env.yml
   with:
     folder: AiTestGenerotorAnalisis
     script: AiTestGenerotorAnalisisTest.sh