name: pipeline

on:
    push


jobs:
    build-plugin:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: ./AiUnitTestPlugin

        steps:
            - uses: actions/checkout@v3
            - name: Set up JDK 21
              uses: actions/setup-java@v3
              with:
                java-version: '21'
                distribution: 'temurin'
                cache: maven
            - name: Grant execute permission for Gradle wrapper
              run: chmod +x ./gradlew
            - name: Build with Gradle
              run: ./gradlew build
