name: pipeline

on: push

jobs:
  prebuild:
    uses: ./.github/workflows/ci-base.yml
    with:
      gradle_command: prebuild
  run-project-test:
    uses: ./.github/workflows/CI-env.yml
    steps:
      - name: run test
        env:
          GRADLE_ENTERPRISE_TERMS_OF_SERVICE_ACCEPTED: "yes"
          GRADLE_ENTERPRISE_TERMS_OF_SERVICE_URL: "https://gradle.com/terms-of-service"
          DOCKER_NETWORK: my-net
          OLLAMA_API: "http:/ollama:11434/"
        run: |
          cd AiTestGenerator
          dos2unix gradlew
          chmod +x gradlew
          ./gradlew test --scan --no-daemon -Dorg.gradle.jvmargs=-XX:+UseContainerSupport